# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_home(object):
    def setupUi(self, home):
        home.setObjectName("home")
        home.resize(846, 586)
        home.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        home.setAutoFillBackground(True)
        home.setLocale(QtCore.QLocale(QtCore.QLocale.Spanish, QtCore.QLocale.Panama))
        self.centralWidget = QtWidgets.QWidget(home)
        self.centralWidget.setObjectName("centralWidget")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(280, 10, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Utopia")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(220, 440, 481, 81))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bt_lexico = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.bt_lexico.setObjectName("bt_lexico")
        self.horizontalLayout.addWidget(self.bt_lexico)
        self.bt_sintactico = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.bt_sintactico.setObjectName("bt_sintactico")
        self.horizontalLayout.addWidget(self.bt_sintactico)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(360, 80, 471, 331))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.tx_lexico = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.tx_lexico.setObjectName("tx_lexico")
        self.verticalLayout.addWidget(self.tx_lexico)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.tx_sintactico = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.tx_sintactico.setObjectName("tx_sintactico")
        self.verticalLayout.addWidget(self.tx_sintactico)
        self.tx_ingreso = QtWidgets.QTextEdit(self.centralWidget)
        self.tx_ingreso.setGeometry(QtCore.QRect(20, 80, 321, 331))
        self.tx_ingreso.setObjectName("tx_ingreso")
        self.bt_archivo = QtWidgets.QPushButton(self.centralWidget)
        self.bt_archivo.setGeometry(QtCore.QRect(20, 420, 91, 22))
        self.bt_archivo.setObjectName("bt_archivo")
        self.bt_limpiar = QtWidgets.QPushButton(self.centralWidget)
        self.bt_limpiar.setGeometry(QtCore.QRect(120, 420, 31, 22))
        self.bt_limpiar.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.bt_limpiar.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_limpiar.setIcon(icon)
        self.bt_limpiar.setIconSize(QtCore.QSize(32, 32))
        self.bt_limpiar.setObjectName("bt_limpiar")
        home.setCentralWidget(self.centralWidget)
        self.estado = QtWidgets.QStatusBar(home)
        font = QtGui.QFont()
        font.setFamily("NanumGothicExtraBold")
        font.setPointSize(36)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.estado.setFont(font)
        self.estado.setObjectName("estado")
        home.setStatusBar(self.estado)

        self.retranslateUi(home)
        QtCore.QMetaObject.connectSlotsByName(home)

    def retranslateUi(self, home):
        _translate = QtCore.QCoreApplication.translate
        home.setWindowTitle(_translate("home", "Analizador lexico y sintactico"))
        self.label.setText(_translate("home", "Compilador"))
        self.bt_lexico.setText(_translate("home", "Analizar Lexico"))
        self.bt_sintactico.setText(_translate("home", "Analisis Sintactico"))
        self.label_2.setText(_translate("home", "Analisis Lexico"))
        self.tx_lexico.setPlaceholderText(_translate("home", "Analisis de lexemas"))
        self.label_3.setText(_translate("home", "Analisis Sintactico"))
        self.tx_sintactico.setPlaceholderText(_translate("home", "Analisis de gramatica libre de contexto"))
        self.tx_ingreso.setPlaceholderText(_translate("home", "Ingrese el texto analizay o suba un archivo"))
        self.bt_archivo.setText(_translate("home", "Subir archivo"))

